version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: pnlinh/app:latest
    networks:
    - appnet
    volumes:
    - .:/var/www/html
    working_dir: /var/www/html
    ports:
    - ${APP_PORT}:80
  cache:
    image: redis:alpine
    networks:
    - appnet
    volumes:
    - cachedata:/data
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
    - appnet
    volumes:
    - dbdata:/var/lib/mysql
    ports:
    - ${DB_PORT}:3306
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: pnlinh/node:latest
    networks:
    - appnet
    volumes:
    - .:/opt
    working_dir: /opt
    command: echo Hello Node
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local